### ISSUE TITLE
Transfer back required i18n translation

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/scanner#114]
Hello :wave:

We are currently using [@nodesecure/i18n](https://github.com/NodeSecure/i18n) in `./src/utils/warnings.js` to load translation for some unsafe package warnings.

https://github.com/NodeSecure/scanner/blob/21e91751e7372b21c2421bfde8a4f78d7065f5a3/src/utils/warnings.js#L11-L14

The goal of the issue would be to use the new i18n `extendFromSystemPath` API to transfer back those translations in this project (in a root `i18n` folder).

```js
import * as i18n from "@nodesecure/i18n";

// execute when package is loaded
i18n.extendFromSystemPath("path/to/i18n");

const kDependencyWarnMessage = Object.freeze({
  "@scarf/scarf": await getToken("warnings.disable_scarf"),
  iohook: await getToken("warnings.keylogging")
});
```

This would greatly simplify maintenance by allowing an update of the translations right here.

Translations can be retrieved from i18n repository:
- https://github.com/NodeSecure/i18n/blob/c48806bf2d9cb74627ef5657d0b7c2b463604704/languages/french.js#L118-L121
- https://github.com/NodeSecure/i18n/blob/c48806bf2d9cb74627ef5657d0b7c2b463604704/languages/english.js#L118-L121

**Comment by fabnguess** [comment]
Hi @fraxken  , can i work on this issue?

**Comment by fraxken** [comment]
@fabnguess Already started here: https://github.com/NodeSecure/scanner/pull/144 (I need to finish it)
