### ISSUE TITLE
Add banner

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/scanner#118]
Add the scanner banner at the top of the README file like in [RC project](https://github.com/NodeSecure/rc)

![scanner_banner](https://user-images.githubusercontent.com/4438263/226018084-113c49e6-6c69-4baa-8f84-87e6d695be6d.jpg)

**Comment by Nikhilj007** [comment]
can i work on this issue

**Comment by Nikhilj007** [comment]
@fraxken can I work on this issue.
