### ISSUE TITLE
Add support for npm github: dependency resolver.

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/scanner#15]
I think pacote support the `github:` dependency resolver (like `git+url.git`). It would be really cool to add the possibility to analyze github packages automatically.

**Comment by mbalabash** [comment]
Hey @fraxken 
Yes, I think you are right.
I tried `npx pacote tarball github://github.com/mbalabash/estimo.git#v2.3.0 ./estimo-v2.3.0.tgz`) and looks like it works well. I can try to prepare PR for it.

Am I right that we need to:
1. change `mergeDependencies.js` to add dependency links with `github:` to `customResolvers`
2. change `depWalker.js` to make it process `github:` links in the same way how it works now for `git+` links

?

**Comment by fraxken** [comment]
@mbalabash Yes that's right.

However i think mergeDependencies already add `github:` because of the RegEx (to confirm). However yes the walker was only designed for `git+` what is not great in the light of what is possible.

I also wonder if i missed a case with `git:` (because i'v seen an example in the npm doc).

![image](https://user-images.githubusercontent.com/4438263/143776289-96bd1af3-bba3-410b-b6fc-6209acbd610c.png)

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies

**Comment by fraxken** [comment]
Note: UT are not very good around walker (and i have few cross-os issues to fix).

Also, think to setup an env `NODE_SECURE_TOKEN` with an npm access token (Otherwise you will be limited on the use of the npm registry).

https://docs.npmjs.com/creating-and-viewing-access-tokens

**Comment by mbalabash** [comment]
Yes, `mergeDependencies.js` already will add `github:` and `git:` links. I misread RegEx 😁
OK, then I will start working on PR. Probably will ask some more questions)

**Comment by mbalabash** [comment]
Opened [PR](https://github.com/NodeSecure/scanner/pull/18)

**Comment by fraxken** [comment]
Thanks for the contribution @mbalabash.

**Comment by fraxken** [comment]
@all-contributors please add @mbalabash for code
