### ISSUE TITLE
Re-implement Authors package from zero in the workspaces

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/scanner#224]
Current authors package require a complete rewrite (from zero).

That's what I was trying to do in: https://github.com/NodeSecure/authors/pull/52 (but kinda failed because it was more complicated that I imaginated).

The [domain-check](https://github.com/NodeSecure/domain-check) package should also be merged here (I don't think we need a dedicated workspace for it however).

One of the main goal is to simplify the integration with Scanner. But it will also drastically reduce the maintenance required.

@Kawacrepe

**Comment by Kawacrepe** [comment]
I'm gonna give it a look this weekend in order to make a first draft according our previous discussion
