### ISSUE TITLE
Add support for npm workspaces

### ISSUE THREAD

**Issue by targos** [NodeSecure/scanner#24]
See example in https://github.com/targos/nsecure-workspace

Result of `nsecure cwd` is included in the repo.

Modules structure:
![image](https://user-images.githubusercontent.com/2352663/148760271-18f93b85-f4b9-49fd-9614-f5b696bac1be.png)

node-secure data:
![image](https://user-images.githubusercontent.com/2352663/148760311-8bd81f70-6cfe-4838-b9a3-b475cdf73310.png)

We see that only the top-level `lodash` dependency was analyzed.

**Comment by targos** [comment]
Note that the package-lock does contain information about all the dependencies.

**Comment by fraxken** [comment]
PR opened here: https://github.com/NodeSecure/scanner/pull/25

**Comment by fraxken** [comment]
Available in [v3.3.0](https://github.com/NodeSecure/scanner/releases/tag/v3.3.0).
