### ISSUE TITLE
Sort dependencies & scripts for integrity

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/scanner#247]
Integrity hash may differ because the order of the keys in scripts and dependencies are not the same between the manifest in the tarball and the manifest in the registry.

**Comment by RomainLanz** [comment]
We have a similar issue in `@boringnode/bus`, so we decided to use the package [`object-hash`](https://github.com/puleos/object-hash) to create the same hash for an object regardless of the keys order.

**Comment by fraxken** [comment]
Here is the two codes where is required an update

1. Scanner
https://github.com/NodeSecure/scanner/blob/4161e61d79d011c2f9a035d087718ab59114b835/workspaces/scanner/src/npmRegistry.ts#L151-L173

2. Tarball
https://github.com/NodeSecure/scanner/blob/4161e61d79d011c2f9a035d087718ab59114b835/workspaces/tarball/src/manifest.ts#L53-L64
