### ISSUE TITLE
Add option to donate for this project

### ISSUE THREAD

**Issue by mbalabash** [NodeSecure/scanner#27]
Hey!
I like this project and planning to use it in my pet project.
@fraxken Have you thought about adding github sponsorships? I would like to donate)

**Comment by fraxken** [comment]
Maybe one day (I'm thinking about working full time on my open source projects). I'm also thinking that maybe some companies could be sponsors of the NodeSecure project (as long as they help financially in one way or another to maintain the project).

Right now i guess the only sponsorship available is to contribute 😄. But thanks for asking :)

**Comment by mbalabash** [comment]
Awesome plans. Good luck!
