### ISSUE TITLE
verdaccio's pkg info does not contain the 'maintainers' field

### ISSUE THREAD

**Issue by alienzhou** [NodeSecure/scanner#36]
We use [Verdaccio](https://verdaccio.org/) as our private proxy registry. However the pkg info it returns does not contain the 'maintainers' & 'author' fields. As a result an error was thrown:

```
xxxx/@nodesecure/cli/node_modules/@nodesecure/scanner/src/utils/warnings.js:31
    for (const { name, email } of dependency.metadata.maintainers) {
                                                      ^
TypeError: dependency.metadata.maintainers is not iterable
    at getDependenciesWarnings (xxxx/@nodesecure/cli/node_modules/@nodesecure/scanner/src/utils/warnings.js:31:55)
    at depWalker (xxxx/@nodesecure/cli/node_modules/@nodesecure/scanner/src/depWalker.js:312:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async cwd (xxxx/@nodesecure/cli/src/commands/scanner.js:49:19)
```

<img width="689" alt="image" src="https://user-images.githubusercontent.com/9822789/162914933-3d4d0012-cf56-46fc-969f-547f36c55096.png">

---

Verdaccio: 5.8.0
Node.js: 16.14.2
NPM: 8.5.0

**Comment by fraxken** [comment]
Thanks for reporting this. I will see to install Verdaccio locally to reproduce and fix the issue.

**Comment by fraxken** [comment]
Just made a fix for this issue: https://github.com/NodeSecure/scanner/pull/47 (going to release with this fix in the weekend i guess).
