### ISSUE TITLE
Difference between two payloads (new API)

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/scanner#70]
Hello 👋

The goal of the feature is to compare two scanner payloads (one older and one recent) and get **informations** and **delta** between them. A feature like this could be very useful in a tool like [CI](https://github.com/NodeSecure/ci).

For example, to find out if new licences have appeared in between. But we can apply this principle to several other elements:

- New maintainers (or some has been removed since).
- New dependencies added

To date I do not know what would be the ideal approach to develop this feature. Do not hesitate to give ideas!

**Comment by tekeuange23** [comment]
Pretty interesting. However,  do I get the old payload to compare with the new I requested?

**Comment by fraxken** [comment]
@tekeuange23 payload are basically just JSON

**Comment by tekeuange23** [comment]
@fraxken it is assumed that the new api we're creating (I've called it `between`) has to take two `packageName` as entries 
But since the between is between two versions of the same package, shouldn't we take in two `version` entries instead

**Comment by jean-michelet** [comment]
Looking into it
